config/routes.rb
Rails.application.routes.draw do
  


  get 'password_resets/new'

  get 'password_resets/edit'

  get 'users/new'

  root 'static_pages#home'
  get  '/help',    to: 'static_pages#help'

  get  '/signup',  to: 'users#new'
  get  '/new_pub', to: 'pubs#new'

  get    '/login',   to: 'sessions#new'
  post   '/login',   to: 'sessions#create'
  delete '/logout',  to: 'sessions#destroy'


  resources :users
  resources :account_activations, only: [:edit]
  resources :password_resets,     only: [:new, :create, :edit, :update]
  resources :pubs do
    resources :microposts
    resources :reviews
    resources :menus
    put :favorite, on: :member
    put :visited, on: :member
    member do
      get :validatee
    end 
  end
  resources :microposts,          only: [:create, :destroy, :edit, :update]
  resources :reviews do
    resources :answers
  end

  resources :answers

	




end

app/models/pub.rb
class Pub < ApplicationRecord
  belongs_to :user
  has_many :microposts, dependent: :destroy
  has_many :reviews, dependent: :destroy
  validates :user_id, presence: true
  validates :address, presence: true
  validates :name, presence: true
  has_many :favorite_pubs
  has_many :favorited_by, through: :favorite_pubs, source: :user

  has_many :visited_pubs 
  has_many :visiteds_by, through: :visited_pubs, source: :pub

  has_one :menu, dependent: :destroy

  def avg_votes

    sum = 0
    self.reviews.each do |review|
      sum = sum + review.vote
    end
    sum = sum.to_f
    if self.reviews.count > 0
      return (sum/self.reviews.count).round(2)
    else return 0
    end
  end


    def validatee
    	self.validated = true
    	self.save
    # redirect_to root_path
  end


end

app/controllers/pubs_controller.rb
class PubsController < ApplicationController
	before_action :logged_in_user, only:[:create, :index, :update, :destroy, :edit]
  before_action :admin_user && :logged_in_user,     only: :destroy

  def new
  	@pub = Pub.new
  end

  def create
    @pub = Pub.new
    if (!params[:pub][:name].present? or params[:pub][:address].nil?)
        
      flash[:danger] = "Error in creating the pub!"
  		render 'new'
  	else
    @pub = current_user.pubs.create(pub_params)
    if @pub.save
      flash[:success] = "Your pub was created!"
      redirect_to root_path
    end
  end
end

  def show
    @pub = Pub.find(params[:id])
    
    @micropost = current_user.microposts.build if logged_in?
    @review = current_user.reviews.build if logged_in?
    @microposts = @pub.microposts.paginate(page: params[:page], :per_page => 10)
    @reviews = @pub.reviews.paginate(page: params[:page], :per_page => 10)

  end

    def destroy
    Pub.find(params[:id]).destroy
    flash[:success] = "Pub deleted"
    redirect_to root_url
  end

  def index
    @pubs = Pub.all.paginate(page: params[:page], :per_page => 15)
  end

  def edit 
    @pub = Pub.find(params[:id])
  end

  def update
    @pub = Pub.find(params[:id])
    if @pub.update_attributes(pub_params)
      flash[:success] = "Pub updated"
      redirect_to @pub
    else
      flash[:danger] = "Error in updating the pub!"
      render 'edit'
    end
  end


  def favorite
    @pub = Pub.find(params[:id])
    type = params[:type]
    if type == "favorite"
      current_user.favorites << @pub
      flash[:success] = "You favorited " + @pub.name
      redirect_to :back

    elsif type == "unfavorite"
      current_user.favorites.delete(@pub)
      flash[:success] = "You unfavorited " + @pub.name
      redirect_to :back

    else
      # Type missing, nothing happens
      flash[:danger] = "Nothing happened"
      redirect_to :back
    end
  end

    def validatee
    pub = Pub.find(params[:id])
    pub.validated = true
    pub.save
    redirect_to root_path
  end
  helper_method :validatee


  def visited
    @pub = Pub.find(params[:id])
    type = params[:type]
    if type == "visited"
      current_user.visiteds << @pub
      flash[:success] = "You visited " + @pub.name
      redirect_to :back

    elsif type == "not visited"
      current_user.visiteds.delete(@pub)
      flash[:success] = "You did not visit " + @pub.name
      redirect_to :back

    else
      flash[:danger] = "Nothing happened"
      redirect_to :back
    end
  end


    private

  	def pub_params
      params.require(:pub).permit(:name, :address, :website, :description)  
  	end
end

app/helpers/pubs_helper.rb
module PubsHelper
end

app/views/pubs/_pub.html.erb
<li id="pub-<%= pub.id %>">
  <span class="pub"><%= link_to pub.name, pub %></span>
  <span class="address"><%= pub.address %></span>
    <% if current_user.admin? %>
    | <%= link_to "delete", pub, method: :delete,
                                  data: { confirm: "You sure?" } %>
<% if !pub.validated %>
    | <%= link_to "validate", validatee_pub_path(pub) %>
<% end %>
  <% end %>
</li>

app/views/pubs/edit.html.erb
<% provide(:title, "Edit pub") %>
<h1>Update your Pub</h1>

<div class="row">
  <div class="col-md-6 col-md-offset-3">
    <%= form_for(@pub) do |f| %>
      <%= render 'shared/error_messages', object: f.object %>

      <%= f.label :name %>
      <%= f.text_field :name, class: 'form-control' %>

      <%= f.label :address %>
      <%= f.text_field :address, class: 'form-control' %>

      <%= f.label :website %>
      <%= f.text_field :website, class: 'form-control' %>

      <%= f.label :description %>
      <%= f.text_area :description, class: 'form-control' %>
      
      <%= f.submit "Save changes", class: "btn btn-primary" %>
    <% end %>
  </div>
</div>

app/views/pubs/index.html.erb
      <% provide(:title, "All pubs") %>
      <ol class="pubs">
		<%for pub in Pub.all %>
			<% if pub.validated%>
        		<%= render pub %>
    		<%end%>
		<%end%> 
        <%= will_paginate @pubs %>
      </ol>

app/views/pubs/new.html.erb
<% provide(:title, 'Create your own pub') %>
<h1>Create your own pub</h1>

<div class="row">
  <div class="col-md-6 col-md-offset-3">
    <%= form_for(@pub) do |f| %>
      <%= render 'shared/pub_error_messages' %>

      <%= f.label :name %>
      <%= f.text_field :name, class: 'form-control' %>

      <%= f.label :address %>
      <%= f.text_field :address, class: 'form-control' %>


      <%= f.submit "Create my pub", class: "btn btn-primary" %>
    <% end %>
  </div>
</div>

app/views/pubs/show.html.erb
<% provide(:title, @pub.name) %>
<% if logged_in? && current_user == @pub.user%>
  You are the owner of this pub!
  <br>
  <% if !@pub.validated %> The pub still has to be validated by the administrator!
  <% end %>

<%= link_to "Upload menu", new_pub_menu_path(@pub), class: 'btn btn-primary'  %>
  <% if @pub.menu %>
    <%= link_to "Delete menu", pub_menu_path(@pub, @pub.menu), method: :delete,
                                  data: { confirm: "You sure?" }, class: 'btn btn-primary' %>
  <% end %>
<% end %>

<% if current_user.admin? or current_user == @pub.user %>
    <%= link_to "Delete this pub", @pub, method: :delete, data: { confirm: "You sure?" }, class: 'btn btn-primary' %>
<% if !current_user.admin? or current_user == @pub.user %>
    <%= link_to "Edit pub's informations", edit_pub_path(@pub), class: 'btn btn-primary'  %>
<% end %>
<% end %>
<%= content_tag :div, '', id: 'mycontainer', data: { source: @pub.address } %>

<head>

    <style>
       #map {
        height: 400px;
        width: 100%;
       }
    </style>
  </head>
  <body>
    <h3>Pub's position</h3>
    <div id="map"></div>
    <script>

      function initMap() {

        geocoder = new google.maps.Geocoder();
        var latlng = new google.maps.LatLng(41.8, 12.5);
        var mapOptions = {
          zoom: 16,
          center: latlng
        }
        map = new google.maps.Map(document.getElementById('map'), mapOptions);

        var address = $('#mycontainer').data('source');

        geocoder.geocode( { 'address': address}, function(results, status) {
        if (status == 'OK') {
          map.setCenter(results[0].geometry.location);
          var marker = new google.maps.Marker({
            map: map,
            position: results[0].geometry.location
          });
        } else {
          alert('Geocode was not successful for the following reason: ' + status);
      }
    });


      }
    </script>

<script async defer
    src="https://maps.googleapis.com/maps/api/js?key=AIzaSyAVsAo1j0yYW6eY-kKtqjy-IMLnSt4NV0U&callback=initMap">
    </script>


  </body>

<div class="row">
<div class="col-md-2">
<%= image_tag ("yellow_beer.png")%>
</div>
  <div class="col-md-8">
      <h1>
        <%= @pub.name %>
        <br>
        <h2> <%= @pub.address %> </h2>
        <h2> <%= @pub.description %> </h2>
        <h3>
<% if @pub.website%>
        <%= link_to "Visit website", "http://"+@pub.website %>
<% end %>
        <br>
        This pub was visited <%= pluralize((@pub.visited_pubs.count), "time") %>
        <br>
        Ratings:<%= @pub.avg_votes %>/5
        </h3>
        </h1>
  </div>
<div class="col-md-2">
<%= image_tag ("yellow_beer.png")%>
</div>
</div>

<div align="center">
    <% if !current_user.admin? && current_user != @pub.user %>
    <% if current_user.favorites.include?(@pub) %>
    <%= link_to "Unfavorite", favorite_pub_path(@pub, type: "unfavorite"), method: :put, class: 'btn btn-primary'%>
    <% else %>
      <%= link_to "Favorite",   favorite_pub_path(@pub, type: "favorite"), method: :put, class: 'btn btn-primary' %>
    <% end %>
    <% if current_user.visiteds.include?(@pub) %>
  <%= link_to "I have not been here!",   visited_pub_path(@pub, type: "not visited"), method: :put, class: 'btn btn-primary' %>
  <% else %>
  <%= link_to "I have been here!",   visited_pub_path(@pub, type: "visited"), method: :put, class: 'btn btn-primary' %>
  <% end %> 
  <% end %>
      <% if @pub.menu %>
        <%= link_to "See menu", @pub.menu.document.url, class: 'btn btn-primary', target: '_blank'%> 
        <% end %>
</div>

  <div class="row">
    <aside class="col-md-4">
    <% if logged_in? && current_user == @pub.user%>
      <section class="user_info">
      </section>
      <section class="micropost_form">
        <%= render 'shared/micropost_form' %>
      </section>
    <% end %>
    </aside>

    <aside class="col-md-2">
    </aside>


    <aside class="col-md-4">
    <% if logged_in? && !current_user?(@pub.user) && !current_user.admin?%>
      <section class="review_form">
        <%= render 'shared/review_form' %>
      </section>
      <% end %>
    </aside>

        <aside class="col-md-2">
    </aside>
</div>




<div class="row">
    <div class="col-md-6">
    <% if @pub.microposts.count>=0 %>
      <h3>Microposts (<%= @pub.microposts.count %>)</h3>
      <ol class="microposts">
        <%= render @microposts %>
      </ol>
      <%= will_paginate @microposts%>
    <% end %>
  </div>

  <div class="col-md-6">
    <% if @pub.reviews.count>=0 %>
      <h3>Reviews (<%= @pub.reviews.count %>)</h3>
      <ol class="reviews">
        <%= render @reviews %>
      </ol>
      <%= will_paginate @reviews %>
    <% end %>
  </div>
</div>