config/routes.rb
Rails.application.routes.draw do
  


  get 'password_resets/new'

  get 'password_resets/edit'

  get 'users/new'

  root 'static_pages#home'
  get  '/help',    to: 'static_pages#help'

  get  '/signup',  to: 'users#new'
  get  '/new_pub', to: 'pubs#new'

  get    '/login',   to: 'sessions#new'
  post   '/login',   to: 'sessions#create'
  delete '/logout',  to: 'sessions#destroy'


  resources :users
  resources :account_activations, only: [:edit]
  resources :password_resets,     only: [:new, :create, :edit, :update]
  resources :pubs do
    resources :microposts
    resources :reviews
    resources :menus
    put :favorite, on: :member
    put :visited, on: :member
    member do
      get :validatee
    end 
  end
  resources :microposts,          only: [:create, :destroy, :edit, :update]
  resources :reviews do
    resources :answers
  end

  resources :answers

	




end

app/controllers/reviews_controller.rb
class ReviewsController < ApplicationController
before_action :logged_in_user, only: [:create, :destroy, :edit, :update, :show]

  def create
  	@pub = Pub.find(params[:pub_id])
  	input = review_params.merge(pub: @pub)
    @review = current_user.reviews.build(input)
    if @review.save
      flash[:success] = "Review created!"
      redirect_to(:back)
    else
      flash[:danger] = "Error in creating the review!"
      render 'static_pages/home'
    end
  end

    def destroy
    Review.find(params[:id]).destroy
    flash[:success] = "Review deleted"
    redirect_to(:back)
  end


  def show
  	@review = Review.find(params[:id])
  	@answer = Answer.new
  end

  def edit 
    @review = Review.find(params[:id])
  end

  def update
    @review = Review.find(params[:id])
    
    if @review.update_attributes(review_params)
      flash[:success] = "Review updated"
      redirect_to pub_path(@review.pub)
    else
      flash[:danger] = "Review was not modified"
      redirect_to(:back)
    end
  end


  private

    def review_params
      params.require(:review).permit(:content, :vote)
    end
end

app/helpers/reviews_helper.rb
module ReviewsHelper
end

app/views/reviews/_review.html.erb
<li id="review-<%= review.id %>">
  <span class="review"><%= link_to review.user.name, review.user %> voted <%= review.vote %></span>
  <span class="content"><%= review.content %></span>
  <span class="timestamp">
    Posted <%= time_ago_in_words(review.created_at) %> ago.
  
      <% if current_user.admin? or review.user == current_user %>
    | <%= link_to "delete", review, method: :delete,
                                  data: { confirm: "You sure?" } %>
  <% end %>
        <% if review.user == current_user %>
    | <%= link_to "edit", edit_review_path(review) %>
  <% end %>

   <% if logged_in? %>
    | <%= link_to "Answers"+'('+review.answers.count.to_s+')', review_path(review)  %>
  <% end %>
</span>

</li>

app/views/reviews/edit.html.erb
Your review content is: 
<span class="content"><%= @review.content %></span>

<div class="row">
<aside class="col-md-4">
      <section class="review_form">
        <%= render 'shared/review_form' %>
      </section>
    </aside>
</div>

app/views/reviews/show.html.erb
<%= link_to @review.user.name, @review.user %>
<br>
<span class="content"><%= @review.content %></span>
<br>
<div class="col-md-0">
    <% if @review.answers.any? %>
      <h3>Answers (<%= @review.answers.count %>)</h3>
      <ol class="answers">
        <%= render @review.answers %>
      </ol>
    <% end %>
  </div>
<% if !current_user.admin?%>
<div class="row">
<aside class="col-md-4">
      <section class="review_form">
        <%= render 'shared/answer_form' %>
      </section>
    </aside>
</div>
<%end%>