config/routes.rb
Rails.application.routes.draw do
  


  get 'password_resets/new'

  get 'password_resets/edit'

  get 'users/new'

  root 'static_pages#home'
  get  '/help',    to: 'static_pages#help'

  get  '/signup',  to: 'users#new'
  get  '/new_pub', to: 'pubs#new'

  get    '/login',   to: 'sessions#new'
  post   '/login',   to: 'sessions#create'
  delete '/logout',  to: 'sessions#destroy'


  resources :users
  resources :account_activations, only: [:edit]
  resources :password_resets,     only: [:new, :create, :edit, :update]
  resources :pubs do
    resources :microposts
    resources :reviews
    resources :menus
    put :favorite, on: :member
    put :visited, on: :member
    member do
      get :validatee
    end 
  end
  resources :microposts,          only: [:create, :destroy, :edit, :update]
  resources :reviews do
    resources :answers
  end

  resources :answers

	




end

app/views/layouts/_header.html.erb
<header class="navbar navbar-fixed-top navbar-inverse">
  <div class="container">
    <%= link_to "PUB FINDER", root_path, id: "logo" %>
    <nav>
      <ul class="nav navbar-nav navbar-right">
        <li><%= link_to "Home", root_path %></li>
        <li><%= link_to "Help", help_path %></li>
        <% if logged_in? %>
          <% if @current_user.pubs.count > 0 %>
            <li class="dropdown">
            <a href="#" class="dropdown-toggle" data-toggle="dropdown" id="your_pubs">
              Your pubs <b class="caret"></b>
            </a>
            <ul class="dropdown-menu">
              <% for pub in @current_user.pubs %>
              <li><a href=<%=pub_path(pub.id.to_s)%> id="pub"> <%= pub.name %> </a></li>
              <% end %>
            </ul>
          </li>
          <% end %>
          <li><%= link_to "Users", users_path %></li>
          <li><%= link_to "All pubs", pubs_path %></li>
          <li class="dropdown">
            <a href="#" class="dropdown-toggle" data-toggle="dropdown" id="account">
              Account <b class="caret"></b>
            </a>
            <ul class="dropdown-menu">
              <li><%= link_to "Profile", current_user %></li>
              <li><%= link_to "Settings", edit_user_path(current_user) %></li>
              <li class="divider"></li>
              <li>
                
                <li><a href="/logout" data-method="delete" id="logout"><span class="glyphicon glyphicon-log-out"></span> Logout</a>
                </li>
              </li>
            </ul>
          </li>
        <% else %>
          <li><a href="/login"><span class="glyphicon glyphicon-log-in"></span> Login</a></li>
        <% end %>
      </ul>
    </nav>
  </div>
</header>

app/views/layouts/_shim.html.erb
<!--[if lt IE 9]>
  <script src="//cdnjs.cloudflare.com/ajax/libs/html5shiv/r29/html5.min.js">
  </script>
<![endif]-->

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title><%= full_title(yield(:title)) %></title>
    <%= csrf_meta_tags %>
    <%= stylesheet_link_tag    'application', media: 'all',
                                              'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    <%= render 'layouts/shim' %>

<%= favicon_link_tag 'favicon.ico' %>
  </head>
  <body >
    <%= render 'layouts/header' %>
    <div class="container">
      <% flash.each do |message_type, message| %>
        <div class="alert alert-<%= message_type %>"><%= message %></div>
      <% end %>
      <%= yield %>

    </div>
  </body>
</html>